### PR TITLE
Fixing world reset for local objects 

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS

@jframos 
### DESCRIPTION

Adding region name to remote big files name
Adding region name to container name
Fixing reset local objects world

### CODE REVIEW

**Comment by jframos** [comment]
Perhaps, instead of issuing hotfixes, we should release a new version of this component at the end of each week or something like this. What do you think? @flopezag

**Comment by flopezag** [comment]
I suggest to do only hotfixes when there is a big problem that impeded the normal functionality of the application. If we can work with the bug explaining it, I suggest to wait until the end of the sprint in order to update the new version of the application.

**Comment by jframos** [comment]
@geonexus I think this is not a _major_ problem and we can leave it to be released at the end of the Sprint.

**Comment by flopezag** [comment]
I suggest then close this PR. Any comments?

**Comment by jframos** [comment]
Closed.

**Pull request closed without merging**
