### PR TITLE
Reset phoneme data_received before connect and wait for a new signal

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS

@jframos @pratid 
### DESCRIPTION

Reset phoneme data_received before connect and wait for a new signal

### CODE REVIEW

**Comment by pratid** [comment]
I'm not sure why this is necessary, but in any case I think we'd better include it as part of the new object construction (i.e., in `client = DbusPhoneHomeClient(self.logger)`)

**Comment by jframos** [comment]
This issue fixes **CLAUDIA-5305**.
LGTM

**Comment by pratid** [comment]
LGTM, but this constitutes techdebt and has to be analyzed and solved in a future.

**Comment by jframos** [comment]
New feature in the backlog: **CLAUDIA-5429**

**Pull request merged**
